-- Esquema H2 del taller Biblioteca 1.0. Se ejecuta antes de data.sql.

-- 1) USUARIOS: catálogo de lectores (sin dependencias)
CREATE TABLE IF NOT EXISTS usuarios (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email  VARCHAR(120) NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email)          -- R2: email único
);

-- 2) LIBROS: catálogo de libros (sin dependencias)
CREATE TABLE IF NOT EXISTS libros (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo     VARCHAR(200) NOT NULL,
    autor      VARCHAR(150) NOT NULL,
    isbn       VARCHAR(20)  NOT NULL,
    disponible BOOLEAN      NOT NULL DEFAULT TRUE,       -- lo controla el Service (R3/R10)
    CONSTRAINT uk_libros_isbn UNIQUE (isbn)              -- R1: ISBN único
);

-- 3) PRESTAMOS: depende de usuarios y libros (dos relaciones N:1)
CREATE TABLE IF NOT EXISTS prestamos (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libro_id                  BIGINT      NOT NULL,
    usuario_id                BIGINT      NOT NULL,
    fecha_prestamo            DATE        NOT NULL,      -- la asigna el servidor (R9)
    fecha_devolucion_prevista DATE        NOT NULL,      -- hoy + 14 días (R5)
    fecha_devolucion          DATE,                      -- NULL = préstamo activo
    estado                    VARCHAR(20) NOT NULL,
    CONSTRAINT fk_prestamos_libro
        FOREIGN KEY (libro_id) REFERENCES libros (id),   -- Libro 1 -- * Prestamo
    CONSTRAINT fk_prestamos_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id), -- Prestamo * -- 1 Usuario
    CONSTRAINT ck_prestamos_estado
        CHECK (estado IN ('PRESTADO', 'DEVUELTO'))       -- R6
);

-- Índices para las consultas frecuentes del repositorio
CREATE INDEX IF NOT EXISTS idx_prestamos_libro
    ON prestamos (libro_id);

CREATE INDEX IF NOT EXISTS idx_prestamos_usuario
    ON prestamos (usuario_id);

CREATE INDEX IF NOT EXISTS idx_prestamos_estado
    ON prestamos (estado);

